# Generated by Django 4.2.7 on 2023-11-13 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carreras',
            fields=[
                ('ID_Carrera', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_Carrera', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profesores',
            fields=[
                ('ID_Profesor', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('Apellido', models.CharField(max_length=100)),
                ('Correo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('ID_Estudiante', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('Apellido', models.CharField(max_length=100)),
                ('Edad', models.IntegerField()),
                ('Carrera_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Semana17App.carreras')),
            ],
        ),
        migrations.CreateModel(
            name='Asignaturas',
            fields=[
                ('ID_Asignatura', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_Asignatura', models.CharField(max_length=100)),
                ('Carrera_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Semana17App.carreras')),
                ('ID_Profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Semana17App.profesores')),
            ],
        ),
    ]
